print("ZADANIE NR 10")
lista = []
a = ("The Dark Knight")
b = ("12 Angry Men")
c = ("Good will haunting")
d = ("Trainspotting")
e = ("Pulp fiction")
lista.append(a)
lista.append(b)
lista.append(c)
lista.append(d)
lista.append(e)
lista.sort()
print(lista)